config/routes.rb
ReferralServerRuby::Application.routes.draw do

  resources :procedures, defaults: {format: :json}

  devise_for :users, path: '', path_names: {registration: 'sign_up'}, controllers: {sessions: :sessions, registrations: :registrations, passwords: :passwords}, token_authentication_key: 'authentication_token'

  resources :addresses, defaults: {format: :json}

  resources :attachments, defaults: {format: :json}

  resources :notes, defaults: {format: :json}

  resources :patients, defaults: {format: :json} do
    get :search, to: 'patients#search', on: :collection
  end

  resources :referrals, defaults: {format: :json} do
    post :template, to: 'referrals#save_template', on: :new
    put :status, to: 'referrals#change_status', on: :member
    get 'practice/:id', to: 'referrals#referrals_by_practice', on: :collection
  end

  resources :practices, defaults: {format: :json} do
    get :search, to: 'practices#search', on: :collection
  end

  resources :practice_invitations, only: [:create, :destroy], defaults: {format: :json}

  get :s3, to: 'attachments#s3_credentials', defaults: {format: :json}

  get 'invitations/:invitation_token', to: 'provider_invitations#show', defaults: {format: :json}
  get 'invitees/:user_id', to: 'provider_invitations#invitees', defaults: {format: :json}
  post 'invitations', to: 'provider_invitations#create', defaults: {format: :json}
  delete 'invitations/:id', to: 'provider_invitations#destroy', defaults: {format: :json}

  get :providers, to: 'users#doctors', defaults: {format: :json}
  get :users, to: 'users#index', defaults: {format: :json}
  get 'users/:id', to: 'users#show', defaults: {format: :json}
  post :users, to: 'users#invite', defaults: {format: :json}
  delete 'users/:id', to: 'users#destroy', defaults: {format: :json}
  put 'users/:id', to: 'users#update', defaults: {format: :json}

  get 'login', to: redirect('/pages/dentalLinks.html')

  get :practice_types, to: "procedures#practice_types"

  root 'referrals#index'

end

app/models/referral.rb
class Referral < ActiveRecord::Base
  include MailHelper
  belongs_to :orig_practice, class_name: 'Practice'
  belongs_to :dest_practice, class_name: 'Practice'

  belongs_to :orig_provider, class_name: 'User'
  belongs_to :dest_provider, class_name: 'User'
  belongs_to :procedure

  belongs_to :patient
  has_many :attachments
  has_many :notes

  accepts_nested_attributes_for :notes

  validates :orig_practice_id, :orig_provider_id, :dest_provider_id, :patient_id, :procedure_id, presence: true


end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  include MailHelper

  before_action :set_referral, only: [:show, :edit, :update, :change_status, :destroy]
  before_action :create_referral, only: [:create, :save_template]
  load_and_authorize_resource
  # GET /referrals
  # GET /referrals.json
  def index
    render json: Referral.all, include: [:dest_provider, :orig_provider, :procedure]
  end

  def referrals_by_practice
    render json: Referral
    .where('orig_practice_id = :id OR dest_practice_id = :id', id: params[:id])
    .where(created_at: params[:start_date]..params[:end_date]),
           include: [:orig_practice, :dest_practice, :dest_provider, :orig_provider, :patient]
  end


  # GET /referrals/1
  # GET /referrals/1.json
  def show
    respond_to do |format|
      format.json { render json: @referral, include: {
          patient: {},
          attachments: {},
          procedure: {include: :practice_type},
          orig_provider: {include: :practice},
          dest_provider: {include: {practice: {include: {users: {}, address: {}}}}},
          notes: {include: :user}} }
    end
  end

  # POST /referrals
  # POST /referrals.json
  def create
    prepare_referral
    @referral.status = :sent

    respond_to do |format|
      if @referral.save
        send_email_to_doctor(@referral.dest_practice)
        format.json { render json: @referral, status: :created }
      else
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  def prepare_referral
    unless @referral.patient_id
      patient = Patient.create(patient_params)
      @referral.patient = patient
    end

    unless @referral.orig_practice_id
      @referral.orig_practice = current_user.practice
    end

    unless @referral.orig_provider_id
      @referral.orig_provider = current_user
    end

    if params[:attachments]
      params[:attachments].each do |attachment|
        @referral.attachments << Attachment.new({filename: attachment[:url], notes: attachment[:notes], referral_id: @referral.id, patient_id: @referral.patient.id})
      end
    end
  end

  #this method is used for saving not-ready referral. It then should be reviewed by provider (doctor) and sent to destination.
  def save_template
    prepare_referral
    @referral.status = :new
    respond_to do |format|
      if @referral.save
        format.json { render json: @referral, status: :created }
      else
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  #PUT /referrals/1/status
  def change_status
    respond_to do |format|
      if @referral.update(status_params)
        send_status_emails (status_params[:status])
        format.json { render json: @referral, status: :ok }
      else
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /referrals/1
  # PATCH/PUT /referrals/1.json
  def update
    prepare_referral
    respond_to do |format|
      if @referral.update(referral_params)
        format.json { render json: @referral, status: :ok }
      else
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referrals/1
  # DELETE /referrals/1.json
  def destroy
    @referral.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def send_status_emails(status)
    recipients = @referral.orig_practice.users
    send_email({
                   template_name: "referral-status",
                   template_content: {},
                   global_merge_vars: {},
                   merge_vars: recipients.map { |u| {
                       rcpt: u.email,
                       vars: [
                           {name: 'FIRST_NAME', content: u.first_name},
                           {name: 'LAST_NAME', content: u.last_name},
                           {name: 'STATUS', content: status},
                           {name: 'REFERRAL_ID', content: @referral.id}
                       ]
                   } },
                   recipients: recipients.map { |u| {email: u.email, name: "#{u.first_name} #{u.last_name}", type: 'to'} }
               })
  end


  def send_email_to_doctor(dest_practice)
    recipients = @referral.orig_practice.users
    send_email({
                   template_name: 'referral-notification',
                   template_content: {},
                   merge_vars:
                       recipients.map { |u| {
                           rcpt: u.email,
                           vars: [
                               {name: 'FIRST_NAME', content: u.first_name},
                               {name: 'LAST_NAME', content: u.last_name},
                               {name: 'REFERRAL_ID', content: @referral.id}
                           ]
                       } },
                   recipients: recipients.map { |u| {email: u.email, name: "#{u.first_name} #{u.last_name}", type: 'to'} }
               })
  end

# Use callbacks to share common setup or constraints between actions.
  def set_referral
    @referral = Referral.find(params[:id])
  end

  def create_referral
    @referral = Referral.new(referral_params)
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def referral_params
    params.require(:referral).permit(:orig_practice_id, :dest_practice_id, :patient_id, :memo, :status, :teeth, :procedure_id, :dest_provider_id, notes_attributes: [:id, :message, :created_at, :referral_id, :user_id])
  end

  def practice_invitation_params
    params.require(:practice).permit(:contact_first_name, :contact_last_name, :contact_email, :practice_name, :contact_phone)
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :birthday, :email, :phone)
  end

  def status_params
    params.require(:referral).permit(:status)
  end

end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/referrals/_form.html.erb
<%= form_for(@referral) do |f| %>
  <% if @referral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@referral.errors.count, "error") %> prohibited this referral from being saved:</h2>

      <ul>
      <% @referral.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :orig_practice %><br>
    <%= f.collection_select :orig_practice_id, Practice.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :dest_practice %><br>
    <%= f.collection_select :dest_practice_id, Practice.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :patient %><br>
    <%= f.collection_select :patient_id, Patient.all, :id, :full_name, prompt: true   %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/referrals/edit.html.erb
<h1>Editing referral</h1>

<%= render 'form' %>

<%= link_to 'Show', @referral %> |
<%= link_to 'Back', referrals_path %>

app/views/referrals/index.html.erb
<h1>Listing referrals</h1>

<table>
  <thead>
    <tr>
      <th>Orig practice</th>
      <th>Dest practice</th>
      <th>Patient</th>
      <th>Memo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @referrals.each do |referral| %>
      <tr>
        <td><%= referral.orig_practice_id %></td>
        <td><%= referral.dest_practice_id %></td>
        <td><%= referral.patient_id %></td>
        <td><%= referral.memo %></td>
        <td><%= link_to 'Show', referral %></td>
        <td><%= link_to 'Edit', edit_referral_path(referral) %></td>
        <td><%= link_to 'Destroy', referral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referral', new_referral_path %>

app/views/referrals/new.html.erb
<h1>New referral</h1>

<%= render 'form' %>

<%= link_to 'Back', referrals_path %>

app/views/referrals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orig practice:</strong>
  <%= @referral.orig_practice %>
</p>

<p>
  <strong>Dest practice:</strong>
  <%= @referral.dest_practice %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @referral.patient %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @referral.memo %>
</p>

<%= link_to 'Edit', edit_referral_path(@referral) %> |
<%= link_to 'Back', referrals_path %>