config/routes.rb
ReferralServerRuby::Application.routes.draw do

  resources :procedures, defaults: {format: :json}

  devise_for :users, path: '', path_names: {registration: 'sign_up'}, controllers: {sessions: :sessions, registrations: :registrations, passwords: :passwords}, token_authentication_key: 'authentication_token'

  resources :addresses, defaults: {format: :json}

  resources :attachments, defaults: {format: :json}

  resources :notes, defaults: {format: :json}

  resources :patients, defaults: {format: :json} do
    get :search, to: 'patients#search', on: :collection
  end

  resources :referrals, defaults: {format: :json} do
    post :template, to: 'referrals#save_template', on: :new
    put :status, to: 'referrals#change_status', on: :member
    get 'practice/:id', to: 'referrals#referrals_by_practice', on: :collection
  end

  resources :practices, defaults: {format: :json} do
    get :search, to: 'practices#search', on: :collection
  end

  resources :practice_invitations, only: [:create, :destroy], defaults: {format: :json}

  get :s3, to: 'attachments#s3_credentials', defaults: {format: :json}

  get 'invitations/:invitation_token', to: 'provider_invitations#show', defaults: {format: :json}
  get 'invitees/:user_id', to: 'provider_invitations#invitees', defaults: {format: :json}
  post 'invitations', to: 'provider_invitations#create', defaults: {format: :json}
  delete 'invitations/:id', to: 'provider_invitations#destroy', defaults: {format: :json}

  get :providers, to: 'users#doctors', defaults: {format: :json}
  get :users, to: 'users#index', defaults: {format: :json}
  get 'users/:id', to: 'users#show', defaults: {format: :json}
  post :users, to: 'users#invite', defaults: {format: :json}
  delete 'users/:id', to: 'users#destroy', defaults: {format: :json}
  put 'users/:id', to: 'users#update', defaults: {format: :json}

  get 'login', to: redirect('/pages/dentalLinks.html')

  get :practice_types, to: "procedures#practice_types"

  root 'referrals#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :address
  has_many :attachment
  has_many :referrals

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :create_patient, only: [:create]
  load_and_authorize_resource

  # GET /patients
  # GET /patients.json
  def index
    render json: Patient.all, status: :ok
  end

  def search
    render json: Patient.where('first_name LIKE :search OR last_name LIKE :search OR email LIKE :search', search: "%#{params[:search]}%").limit(10)
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    respond_to do |format|
      if @patient.save
        format.json { render json: @patient, status: :created }
      else
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.json { head :no_content }
      else
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

  def create_patient
    @patient = Patient.new(patient_params)
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :salutation, :middle_initial, :birthday, :email, :phone)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>