config/routes.rb
ReferralServerRuby::Application.routes.draw do

  resources :procedures, defaults: {format: :json}

  devise_for :users, path: '', path_names: {registration: 'sign_up'}, controllers: {sessions: :sessions, registrations: :registrations, passwords: :passwords}, token_authentication_key: 'authentication_token'

  resources :addresses, defaults: {format: :json}

  resources :attachments, defaults: {format: :json}

  resources :notes, defaults: {format: :json}

  resources :patients, defaults: {format: :json} do
    get :search, to: 'patients#search', on: :collection
  end

  resources :referrals, defaults: {format: :json} do
    post :template, to: 'referrals#save_template', on: :new
    put :status, to: 'referrals#change_status', on: :member
    get 'practice/:id', to: 'referrals#referrals_by_practice', on: :collection
  end

  resources :practices, defaults: {format: :json} do
    get :search, to: 'practices#search', on: :collection
  end

  resources :practice_invitations, only: [:create, :destroy], defaults: {format: :json}

  get :s3, to: 'attachments#s3_credentials', defaults: {format: :json}

  get 'invitations/:invitation_token', to: 'provider_invitations#show', defaults: {format: :json}
  get 'invitees/:user_id', to: 'provider_invitations#invitees', defaults: {format: :json}
  post 'invitations', to: 'provider_invitations#create', defaults: {format: :json}
  delete 'invitations/:id', to: 'provider_invitations#destroy', defaults: {format: :json}

  get :providers, to: 'users#doctors', defaults: {format: :json}
  get :users, to: 'users#index', defaults: {format: :json}
  get 'users/:id', to: 'users#show', defaults: {format: :json}
  post :users, to: 'users#invite', defaults: {format: :json}
  delete 'users/:id', to: 'users#destroy', defaults: {format: :json}
  put 'users/:id', to: 'users#update', defaults: {format: :json}

  get 'login', to: redirect('/pages/dentalLinks.html')

  get :practice_types, to: "procedures#practice_types"

  root 'referrals#index'

end

app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :address
  belongs_to :practice_type

  has_many :practice_invitations
  has_many :referrals
  has_many :users

  accepts_nested_attributes_for :address

  validates :name, presence: true
  validates :address, presence: true, unless: :invited?

  before_save :update_stripe

  private

  def invited?
    status == :invite
  end

  def update_stripe

    if self.stripe_customer_id.nil?
      if !stripe_token.present?
        raise "We're doing something wrong -- this isn't supposed to happen"
      end

      customer = Stripe::Customer.create(
        :email => account_email,
        :description => name,
        :card => stripe_token
      )
      #self.last_4_digits = customer.active_card.last4
      response = customer.update_subscription({:plan => "referral-premium"})
    else
      customer = Stripe::Customer.retrieve(stripe_customer_id)

      if stripe_token.present?
        customer.card = stripe_token
      end

      # in case they've changed
      customer.email = account_email
      customer.description = name

      customer.save

      #self.last_4_digits = customer.active_card.last4
    end

    self.stripe_customer_id = customer.id
    #self.stripe_token = nil
  end
end

app/models/practice_type.rb
class PracticeType < ActiveRecord::Base
  has_many :practices
  has_many :procedures
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]
  before_action :create_practice, only: [:create]
  load_and_authorize_resource except: [:search]

  skip_authorization_check only: [:search]
  skip_before_filter :authenticate_user_from_token!, only: [:search]
  skip_before_filter :authenticate_user!, only: [:search]


  # GET /practices
  # GET /practices.json
  def index
    render json: Practice.all, status: :ok
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    render json: @practice, include: [:address, :users], status: :ok
  end

  def search
    render json: Practice.where("name LIKE :search", search: "%#{params[:search]}%").limit(10), include: [:practice_type, :users]
  end


  # POST /practices
  # POST /practices.json
  def create
    respond_to do |format|
      if @practice.save
        format.json { render json: @practice, status: :created}
      else
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.json { render json: @practice, status: :ok }
      else
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    def create_practice
      @practice = Practice.new(practice_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      params.require(:practice).permit(
          :name,
          :description,
          :address_id,
          :card_number,
          :card_cvc,
          :name_on_card,
          :card_exp_month,
          :card_exp_year,
          :salutation,
          :account_first_name,
          :account_last_name,
          :account_middle_initial,
          :stripe_token,
          :account_email,
          address_attributes: [:id, :street_line_1, :city, :state, :zip, :phone, :website])
    end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_form.html.erb
<%= form_for(@practice) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/practices/edit.html.erb
<h1>Editing practice</h1>

<%= render 'form' %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

app/views/practices/index.html.erb
<h1>Listing practices</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= practice.name %></td>
        <td><%= practice.description %></td>
        <td><%= practice.address %></td>
        <td><%= link_to 'Show', practice %></td>
        <td><%= link_to 'Edit', edit_practice_path(practice) %></td>
        <td><%= link_to 'Destroy', practice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Practice', new_practice_path %>

app/views/practices/new.html.erb
<h1>New practice</h1>

<%= render 'form' %>

<%= link_to 'Back', practices_path %>

app/views/practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @practice.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @practice.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @practice.address %>
</p>

<%= link_to 'Edit', edit_practice_path(@practice) %> |
<%= link_to 'Back', practices_path %>